### ISSUE TITLE
fact: handle CIS level 2

### ISSUE THREAD

**Issue by jessereynolds** [jessereynolds/puppet-os_compliance#3]
The fact needs to handle multiple benchmarks, eg CIS Level 1 and Level 2, separately. Example output: 

```yaml
os_compliance:
  cis_level_1:
    version: cis_windows_2016rtm1607_member_server_1.1.0
    percent_compliant: 20.3448275862069
  cis_level_2:
    version: cis_windows_2016rtm1607_member_server_1.1.0
    percent_compliant: 77.1
```

Currently the code assumes all benchmark yaml files are Level 1, so they'll need to be renamed to include the CIS level.
